# Exclude Redis auto-configuration when using Caffeine profile
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration

# Spring Cache type
spring.cache.type=caffeine
spring.batch.job.enabled=false