server.port=8082

# Staging PostgreSQL / External DB
spring.datasource.url=jdbc:postgresql://staging-db.internal:5432/staging_db
spring.datasource.username=staging_admin
spring.datasource.password=StagingSecurePass123!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Config (Validation mode)
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

spring.batch.job.enabled=false